# Generated by Django 4.0.6 on 2024-09-26 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': '12. Años',
            },
        ),
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuevo', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=False)),
                ('imag_colec_01', models.FileField(blank=True, help_text='vertical', null=True, upload_to='vortice')),
                ('imag_colec_02', models.FileField(blank=True, help_text='horizontal', null=True, upload_to='vortice')),
                ('tema_colec', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_tema_colec', models.CharField(blank=True, max_length=250, null=True)),
                ('detalle', models.TextField(blank=True, max_length=500, null=True)),
                ('principal', models.BooleanField(default=False)),
                ('imag_01', models.FileField(blank=True, help_text='principal Mujer vertical', null=True, upload_to='vortice')),
                ('tema_img_02', models.CharField(blank=True, help_text='principal Mujer articulo nombre', max_length=50, null=True)),
                ('imag_02', models.FileField(blank=True, help_text='principal Mujer articulo  horizontal', null=True, upload_to='vortice')),
                ('tema_img_03', models.CharField(blank=True, help_text='principal Hombre articulo nombre', max_length=50, null=True)),
                ('imag_03', models.FileField(blank=True, help_text='principal Hombre articulo  horizontal', null=True, upload_to='vortice')),
                ('imag_04', models.FileField(blank=True, help_text='principal Hombre vertical', null=True, upload_to='vortice')),
            ],
            options={
                'verbose_name_plural': '2. Coleccion ',
            },
        ),
        migrations.CreateModel(
            name='Colores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': '6. Colores',
            },
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=False)),
                ('video', models.FileField(blank=True, help_text='video 200*200', null=True, upload_to='vortice')),
                ('imagen', models.ImageField(blank=True, help_text='imagenes 200*200', null=True, upload_to='vortice')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('detalle', models.TextField(blank=True, max_length=500, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=999)),
            ],
            options={
                'verbose_name_plural': '11. GifCard',
            },
        ),
        migrations.CreateModel(
            name='Imag_prenda_articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=30, null=True)),
                ('imagen', models.ImageField(blank=True, help_text='100x100', null=True, upload_to='vortice')),
            ],
            options={
                'verbose_name_plural': '3. Imag_prenda_articulo ',
            },
        ),
        migrations.CreateModel(
            name='Meses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mes', models.CharField(blank=True, max_length=10, null=True)),
                ('anio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vortice.anio')),
            ],
            options={
                'verbose_name_plural': '13. Meses',
            },
        ),
        migrations.CreateModel(
            name='MesModa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=False)),
                ('izquierda', models.BooleanField(default=False)),
                ('derecha', models.BooleanField(default=False)),
                ('video', models.FileField(blank=True, help_text='video 200*200', null=True, upload_to='vortice')),
                ('imagen', models.ImageField(blank=True, help_text='imagenes 200*200', null=True, upload_to='vortice')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitulo', models.CharField(blank=True, max_length=100, null=True)),
                ('detalle', models.TextField(blank=True, max_length=500, null=True)),
                ('coleccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vortice.coleccion')),
                ('mes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vortice.meses')),
            ],
            options={
                'verbose_name_plural': '14. Mes Moda',
            },
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_1', models.CharField(blank=True, max_length=100, null=True)),
                ('texto_2', models.CharField(blank=True, max_length=100, null=True)),
                ('texto_3', models.CharField(blank=True, max_length=100, null=True)),
                ('texto_4', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '6. Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Prod_prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_produc', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_produc_01', models.ImageField(blank=True, help_text='vertical', null=True, upload_to='vortice')),
                ('imagen_produc_02', models.ImageField(blank=True, help_text='horizontal', null=True, upload_to='vortice')),
                ('video_produc', models.FileField(blank=True, help_text='video', null=True, upload_to='vortice')),
                ('descripcion_produc', models.TextField(blank=True, max_length=500, null=True)),
                ('material_produc', models.TextField(blank=True, max_length=500, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=999)),
                ('activa_descuento', models.BooleanField(blank=True, default=False, null=True)),
                ('precio_descuent', models.DecimalField(blank=True, decimal_places=2, max_digits=999, null=True)),
            ],
            options={
                'verbose_name_plural': '5. Producto ',
            },
        ),
        migrations.CreateModel(
            name='Seccion_Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(blank=True, max_length=30, null=True)),
                ('imag_cliente_01', models.FileField(blank=True, help_text='vertical', null=True, upload_to='vortice')),
                ('imag_cliente_02', models.FileField(blank=True, help_text='horizontal', null=True, upload_to='vortice')),
            ],
            options={
                'verbose_name_plural': '1. Seccion Cliente ',
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, help_text='video 200*200', null=True, upload_to='vortice')),
                ('imagen', models.ImageField(blank=True, help_text='imagenes 200*200', null=True, upload_to='vortice')),
                ('servicio', models.CharField(blank=True, max_length=100, null=True)),
                ('detalle', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': '10. Servicios',
            },
        ),
        migrations.CreateModel(
            name='Vortice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='vortice')),
                ('logo_horizontal', models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='vortice')),
                ('logo_amarillo', models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='vortice')),
                ('whatsapp', models.CharField(blank=True, max_length=11, null=True)),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('tiktok', models.CharField(blank=True, max_length=100, null=True)),
                ('x', models.CharField(blank=True, max_length=100, null=True)),
                ('pinterest', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube', models.CharField(blank=True, max_length=100, null=True)),
                ('s1_titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('s2_imagen', models.ImageField(blank=True, help_text='imagenes 2000 × 1262 px', null=True, upload_to='vortice')),
                ('s3_imagen', models.ImageField(blank=True, help_text='imagenes 2000 × 1262 px', null=True, upload_to='vortice')),
                ('s4_imagen', models.ImageField(blank=True, help_text='imagenes 2000 × 1262 px', null=True, upload_to='vortice')),
                ('s5_imagen', models.ImageField(blank=True, help_text='imagenes 2000 × 1262 px', null=True, upload_to='vortice')),
                ('s6_imagen', models.ImageField(blank=True, help_text='imagenes 2000 × 1262 px', null=True, upload_to='vortice')),
            ],
            options={
                'verbose_name_plural': '1. Vortice',
            },
        ),
        migrations.CreateModel(
            name='Tipo_articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_articulo', models.CharField(blank=True, max_length=10, null=True)),
                ('imagen_articulo', models.ImageField(blank=True, help_text='100x100', null=True, upload_to='vortice')),
                ('coleccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vortice.coleccion')),
            ],
            options={
                'verbose_name_plural': '4. Tipo de Articulo ',
            },
        ),
        migrations.CreateModel(
            name='Produc_Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, help_text='100x100', null=True, upload_to='vortice')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vortice.colores')),
                ('produc_prenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vortice.prod_prenda')),
            ],
            options={
                'verbose_name_plural': '7.Color de Productos',
            },
        ),
        migrations.AddField(
            model_name='prod_prenda',
            name='tipo_produc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vortice.tipo_articulo'),
        ),
        migrations.CreateModel(
            name='MesModa_galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_1', models.ImageField(blank=True, help_text='horizontal', null=True, upload_to='vortice')),
                ('imagen_2', models.ImageField(blank=True, help_text='vertical', null=True, upload_to='vortice')),
                ('imagen_3', models.ImageField(blank=True, help_text='vertical', null=True, upload_to='vortice')),
                ('imagen_4', models.ImageField(blank=True, help_text='horizontal', null=True, upload_to='vortice')),
                ('imagen_5', models.ImageField(blank=True, help_text='vertical', null=True, upload_to='vortice')),
                ('imagen_6', models.ImageField(blank=True, help_text='vertical', null=True, upload_to='vortice')),
                ('mesmoda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vortice.mesmoda')),
            ],
            options={
                'verbose_name_plural': '15. Mes Moda Galeria Fotos',
            },
        ),
        migrations.AddField(
            model_name='coleccion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vortice.seccion_cliente'),
        ),
    ]
