# Generated by Django 4.0.6 on 2024-09-26 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0002_nu_talla_cami_nu_talla_produ_nu_talla_zapa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nu_talla_cami',
            options={'verbose_name_plural': '8. Numero  Tallas Camisetas  '},
        ),
        migrations.AlterModelOptions(
            name='nu_talla_produ',
            options={'verbose_name_plural': '8.4 Numero Tallas Producto '},
        ),
        migrations.AlterModelOptions(
            name='nu_talla_zapa',
            options={'verbose_name_plural': '8.2 Numero Tallas Zapatos '},
        ),
        migrations.CreateModel(
            name='Talla_Zapato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vortice.prod_prenda')),
                ('talla_zapatos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vortice.nu_talla_zapa')),
            ],
            options={
                'verbose_name_plural': '8.3 Eleccion Tallas Zapatos ',
            },
        ),
        migrations.CreateModel(
            name='Talla_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vortice.prod_prenda')),
                ('talla_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vortice.nu_talla_produ')),
            ],
            options={
                'verbose_name_plural': '8.5 Eleccion Tallas Producto ',
            },
        ),
        migrations.CreateModel(
            name='Talla_Camiseta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vortice.prod_prenda')),
                ('talla_camisetas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vortice.nu_talla_cami')),
            ],
            options={
                'verbose_name_plural': '8.1 Eleccion de Tallas Camisetas  ',
            },
        ),
    ]
