# Generated by Django 4.0.6 on 2024-10-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0008_tipo_articulo_activo_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('detalle', models.TextField(blank=True, max_length=500, null=True)),
                ('imagen', models.ImageField(blank=True, help_text='imagenes 200*200', null=True, upload_to='vortice')),
            ],
            options={
                'verbose_name_plural': '11. SliderCard',
            },
        ),
    ]
