# Generated by Django 4.0.6 on 2022-07-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon_amarillo', models.ImageField(help_text='imagenes 20*20', upload_to='favicon')),
                ('favicon_negro', models.ImageField(help_text='imagenes 20*20', upload_to='favicon')),
                ('logo_horizontal', models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='favicon')),
                ('logo_amarillo', models.ImageField(help_text='imagenes 20*20', upload_to='favicon')),
                ('logo_negro', models.ImageField(help_text='imagenes 20*20', upload_to='favicon')),
                ('representante', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=11, null=True)),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
                ('celular2', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('nosotros', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': '1. Delifrus',
            },
        ),
    ]
