# Generated by Django 4.0.6 on 2022-07-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delifrus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='favicon_amarillo',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='favicon_negro',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='logo_amarillo',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='logo_negro',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='nosotros',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='representante',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='titulo',
        ),
        migrations.AddField(
            model_name='marca',
            name='favicon',
            field=models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='delifrus'),
        ),
        migrations.AddField(
            model_name='marca',
            name='logo_blanco',
            field=models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='delifrus'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='logo_horizontal',
            field=models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='delifrus'),
        ),
    ]
