# Generated by Django 4.0.6 on 2022-07-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delifrus', '0003_clasif_producto_producto_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='caracteristicas',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
