# Generated by Django 4.0.6 on 2022-07-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delifrus', '0004_alter_producto_caracteristicas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='material',
        ),
        migrations.AddField(
            model_name='producto',
            name='materia_prima',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tamanos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
