# Generated by Django 4.0.6 on 2022-07-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delifrus', '0005_remove_producto_material_producto_materia_prima_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='materia_prima',
            new_name='duracion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='tamanos',
            new_name='embalaje',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='caracteristicas',
        ),
        migrations.AddField(
            model_name='producto',
            name='empaque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='ingredientes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='presentaciones',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='sabores',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
