# Generated by Django 4.0.6 on 2022-07-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delifrus', '0006_rename_materia_prima_producto_duracion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_fondo', models.ImageField(blank=True, help_text='slider', null=True, upload_to='delifrus')),
                ('slider_titulo', models.CharField(blank=True, max_length=80, null=True)),
                ('slider_subtitulo', models.CharField(blank=True, max_length=80, null=True)),
                ('slider_detalle', models.TextField(blank=True, max_length=500, null=True)),
                ('sec1_imagen', models.ImageField(blank=True, help_text='cuadrada', null=True, upload_to='delifrus')),
                ('sec1_titulo', models.CharField(blank=True, max_length=80, null=True)),
                ('sec1_subtitulo', models.CharField(blank=True, max_length=80, null=True)),
                ('sec1_detalle', models.TextField(blank=True, max_length=500, null=True)),
                ('sec2_titulo', models.CharField(blank=True, max_length=80, null=True)),
                ('sec2_subtitulo', models.CharField(blank=True, max_length=80, null=True)),
                ('empr_imagen', models.ImageField(blank=True, help_text='cuadrada', null=True, upload_to='delifrus')),
                ('empr_imagen2', models.ImageField(blank=True, help_text='horizontal', null=True, upload_to='delifrus')),
                ('empr_titulo', models.CharField(blank=True, max_length=80, null=True)),
                ('empr_subtitulo', models.CharField(blank=True, max_length=80, null=True)),
                ('empr_detalle', models.TextField(blank=True, max_length=500, null=True)),
                ('fondo_produ', models.ImageField(blank=True, help_text='horizontal', null=True, upload_to='delifrus')),
                ('publicidad', models.ImageField(blank=True, help_text='vertical', null=True, upload_to='delifrus')),
                ('contac_imagen', models.ImageField(blank=True, help_text='cuadrada', null=True, upload_to='delifrus')),
                ('contac_titulo', models.CharField(blank=True, max_length=80, null=True)),
                ('contac_subtitulo', models.CharField(blank=True, max_length=80, null=True)),
                ('contac_detalle', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': '1. Editable',
            },
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'verbose_name_plural': '2. Delifrus'},
        ),
    ]
