# Generated by Django 4.0.6 on 2022-07-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delifrus', '0007_editable_alter_marca_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='editable',
            name='sec3_subtitulo',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='editable',
            name='sec3_titulo',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
