# Generated by Django 4.0.6 on 2022-07-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delifrus', '0008_editable_sec3_subtitulo_editable_sec3_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editable',
            old_name='empr_subtitulo',
            new_name='empr_titulo2',
        ),
        migrations.AddField(
            model_name='editable',
            name='empr_detalle2',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='editable',
            name='empr_imagen2',
            field=models.ImageField(blank=True, help_text='cuadrada', null=True, upload_to='delifrus'),
        ),
    ]
