# Generated by Django 4.0.6 on 2022-07-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delifrus', '0009_rename_empr_subtitulo_editable_empr_titulo2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editable',
            name='empr_detalle3',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='editable',
            name='empr_imagen3',
            field=models.ImageField(blank=True, help_text='cuadrada', null=True, upload_to='delifrus'),
        ),
        migrations.AddField(
            model_name='editable',
            name='empr_titulo3',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
