# Generated by Django 4.0.6 on 2022-07-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delifrus', '0010_editable_empr_detalle3_editable_empr_imagen3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editable',
            name='slider_imagen',
            field=models.ImageField(blank=True, help_text='slider', null=True, upload_to='delifrus'),
        ),
    ]
