# Generated by Django 4.0.6 on 2022-09-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delifrus', '0011_editable_slider_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editable',
            name='contac_imagen',
            field=models.ImageField(blank=True, help_text='cuadrada', null=True, upload_to='delifrus/'),
        ),
        migrations.AlterField(
            model_name='editable',
            name='empr_imagen',
            field=models.ImageField(blank=True, help_text='cuadrada', null=True, upload_to='delifrus/'),
        ),
        migrations.AlterField(
            model_name='editable',
            name='empr_imagen2',
            field=models.ImageField(blank=True, help_text='cuadrada', null=True, upload_to='delifrus/'),
        ),
        migrations.AlterField(
            model_name='editable',
            name='empr_imagen3',
            field=models.ImageField(blank=True, help_text='cuadrada', null=True, upload_to='delifrus/'),
        ),
        migrations.AlterField(
            model_name='editable',
            name='fondo_produ',
            field=models.ImageField(blank=True, help_text='horizontal', null=True, upload_to='delifrus/'),
        ),
        migrations.AlterField(
            model_name='editable',
            name='publicidad',
            field=models.ImageField(blank=True, help_text='vertical', null=True, upload_to='delifrus/'),
        ),
        migrations.AlterField(
            model_name='editable',
            name='sec1_imagen',
            field=models.ImageField(blank=True, help_text='cuadrada', null=True, upload_to='delifrus/'),
        ),
        migrations.AlterField(
            model_name='editable',
            name='slider_fondo',
            field=models.ImageField(blank=True, help_text='slider', null=True, upload_to='delifrus/'),
        ),
        migrations.AlterField(
            model_name='editable',
            name='slider_imagen',
            field=models.ImageField(blank=True, help_text='slider', null=True, upload_to='delifrus/'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='favicon',
            field=models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='delifrus/'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='logo_blanco',
            field=models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='delifrus/'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='logo_horizontal',
            field=models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='delifrus/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='delifrus/'),
        ),
        migrations.AlterField(
            model_name='producto_imagen',
            name='galeria_articulo',
            field=models.ImageField(blank=True, help_text='imagen producto 800x800', null=True, upload_to='delifrus/'),
        ),
    ]
