# Generated by Django 4.0.6 on 2022-07-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='empresas')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas')),
                ('logo_blanco', models.ImageField(blank=True, null=True, upload_to='empresas/')),
                ('logo_gris', models.ImageField(blank=True, null=True, upload_to='empresas')),
                ('logo_negro', models.ImageField(blank=True, null=True, upload_to='empresas')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='empresas')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('tiktok', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube', models.CharField(blank=True, max_length=100, null=True)),
                ('behance', models.CharField(blank=True, max_length=100, null=True)),
                ('estudio', models.TextField(blank=True, max_length=800, null=True)),
                ('mision', models.TextField(blank=True, max_length=400, null=True)),
                ('vision', models.TextField(blank=True, max_length=400, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'verbose_name_plural': '1. Empresas',
            },
        ),
    ]
