# Generated by Django 4.0.6 on 2022-07-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca_benitez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='empresas')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas')),
                ('logo_blanco', models.ImageField(blank=True, null=True, upload_to='empresas/')),
                ('logo_gris', models.ImageField(blank=True, null=True, upload_to='empresas')),
                ('logo_negro', models.ImageField(blank=True, null=True, upload_to='empresas')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='empresas')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('tiktok', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube', models.CharField(blank=True, max_length=100, null=True)),
                ('behance', models.CharField(blank=True, max_length=100, null=True)),
                ('estudio', models.TextField(blank=True, max_length=800, null=True)),
                ('mision', models.TextField(blank=True, max_length=400, null=True)),
                ('vision', models.TextField(blank=True, max_length=400, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'verbose_name_plural': '1. Grupo Benitez ',
            },
        ),
        migrations.AlterModelOptions(
            name='empresas',
            options={'verbose_name_plural': '2. Empresas'},
        ),
        migrations.RenameField(
            model_name='empresas',
            old_name='behance',
            new_name='nombre_marcas',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='estudio',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='favicon',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='logo_blanco',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='logo_gris',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='logo_negro',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='mision',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='tiktok',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='vision',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='youtube',
        ),
        migrations.AddField(
            model_name='empresas',
            name='slider',
            field=models.ImageField(blank=True, null=True, upload_to='slider_marcas'),
        ),
    ]
