# Generated by Django 4.0.6 on 2022-07-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_marca_benitez_alter_empresas_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca_benitez',
            name='estudio',
        ),
        migrations.AddField(
            model_name='marca_benitez',
            name='calle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marca_benitez',
            name='celular2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marca_benitez',
            name='correo_personal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marca_benitez',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marca_benitez',
            name='horario',
            field=models.CharField(blank=True, default=1, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marca_benitez',
            name='horariosb',
            field=models.CharField(blank=True, default=1, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marca_benitez',
            name='mapa',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='marca_benitez',
            name='representante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marca_benitez',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
