# Generated by Django 4.0.6 on 2022-07-09 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_marca_benitez_autor_marca_benitez_frase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca_benitez',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='marca_benitez',
            name='correo_personal',
        ),
        migrations.RemoveField(
            model_name='marca_benitez',
            name='logo_gris',
        ),
        migrations.RemoveField(
            model_name='marca_benitez',
            name='logo_negro',
        ),
        migrations.RemoveField(
            model_name='marca_benitez',
            name='mapa',
        ),
        migrations.RemoveField(
            model_name='marca_benitez',
            name='representante',
        ),
        migrations.RemoveField(
            model_name='marca_benitez',
            name='telefono',
        ),
    ]
