# Generated by Django 4.0.6 on 2022-07-09 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_remove_marca_benitez_calle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca_benitez',
            name='behance',
        ),
    ]
