# Generated by Django 4.0.6 on 2022-07-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_remove_marca_benitez_behance'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='empresas'),
        ),
    ]
