# Generated by Django 4.0.6 on 2022-07-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_empresas_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
