# Generated by Django 4.0.6 on 2022-08-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_empresas_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresas',
            name='link_exterior',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
