# Generated by Django 4.0.6 on 2022-07-06 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficio', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': '3. Zatuar Beneficios',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': '1. Ciudad',
            },
        ),
        migrations.CreateModel(
            name='Clasif_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion_producto', models.CharField(blank=True, max_length=90, null=True)),
            ],
            options={
                'verbose_name_plural': '3. Clasificaciòn de Producto',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_export', models.CharField(blank=True, max_length=100, null=True)),
                ('client_logo', models.FileField(blank=True, help_text='200x200', null=True, upload_to='cliente')),
                ('detalle', models.TextField(blank=True, max_length=500, null=True)),
                ('foto', models.FileField(blank=True, help_text='1280x500', null=True, upload_to='cliente')),
                ('pagweb', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': '8. Clientes',
            },
        ),
        migrations.CreateModel(
            name='Contacto_empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('mapa', models.TextField(blank=True, max_length=500, null=True)),
                ('representante', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_personal', models.CharField(blank=True, max_length=100, null=True)),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
                ('celular2', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo', models.EmailField(max_length=254)),
                ('horario', models.CharField(blank=True, default=1, max_length=100, null=True)),
                ('horariosb', models.CharField(blank=True, default=1, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '3. Contacto Empresa',
            },
        ),
        migrations.CreateModel(
            name='Descarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('principal', models.BooleanField(default=False)),
                ('img', models.FileField(blank=True, null=True, upload_to='descarga')),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='descarga')),
            ],
            options={
                'verbose_name_plural': '9. Descarga',
            },
        ),
        migrations.CreateModel(
            name='Detalles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
                ('image1', models.FileField(blank=True, null=True, upload_to='detalles')),
                ('image2', models.FileField(blank=True, null=True, upload_to='detalles')),
                ('image3', models.FileField(blank=True, null=True, upload_to='detalles')),
            ],
            options={
                'verbose_name_plural': '8. Detalles',
            },
        ),
        migrations.CreateModel(
            name='Galeria_Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(blank=True, null=True, upload_to='inicio')),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': '7. Galeria_Proceso',
            },
        ),
        migrations.CreateModel(
            name='Identidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': '5. Zatuar es',
            },
        ),
        migrations.CreateModel(
            name='Personalizaion_Poducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to='producto')),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '4. Perzonalizacion de Productos',
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, max_length=200, null=True)),
                ('img1', models.FileField(blank=True, null=True, upload_to='inicio')),
                ('ti1', models.CharField(blank=True, max_length=30, null=True)),
                ('img2', models.FileField(blank=True, null=True, upload_to='inicio')),
                ('ti2', models.CharField(blank=True, max_length=30, null=True)),
                ('img3', models.FileField(blank=True, null=True, upload_to='inicio')),
                ('ti3', models.CharField(blank=True, max_length=30, null=True)),
                ('ti4', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': '6. Proceso',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('image_a', models.FileField(blank=True, help_text='100x100', null=True, upload_to='products/')),
                ('image_b', models.FileField(blank=True, help_text='100x100', null=True, upload_to='products/')),
                ('foto_slider', models.FileField(blank=True, null=True, upload_to='producto/')),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True)),
                ('caracteristicas', models.TextField(blank=True, max_length=500, null=True)),
                ('tamanio', models.CharField(blank=True, max_length=30, null=True)),
                ('tala_s', models.BooleanField(default=False)),
                ('tala_m', models.BooleanField(default=False)),
                ('tala_l', models.BooleanField(default=False)),
                ('tala_xl', models.BooleanField(default=False)),
                ('material', models.CharField(blank=True, max_length=500, null=True)),
                ('textura', models.CharField(blank=True, max_length=30, null=True)),
                ('gramaje', models.CharField(blank=True, max_length=30, null=True)),
                ('nuevo', models.BooleanField(default=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('disponivilidad', models.BooleanField(default=True)),
                ('azul', models.BooleanField(default=False)),
                ('amarillo', models.BooleanField(default=False)),
                ('verde', models.BooleanField(default=False)),
                ('naranja', models.BooleanField(default=False)),
                ('rojo', models.BooleanField(default=False)),
                ('plomo', models.BooleanField(default=False)),
                ('gris', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('clasif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zatuar.clasif_producto')),
            ],
        ),
        migrations.CreateModel(
            name='Redes_sociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube', models.CharField(blank=True, max_length=100, null=True)),
                ('behance', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '4. Redes Sociales',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('slider', models.FileField(blank=True, help_text='1884x529', null=True, upload_to='slider')),
            ],
            options={
                'verbose_name_plural': '1. Slider',
            },
        ),
        migrations.CreateModel(
            name='Zatuar_marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, null=True, upload_to='empresa/logo/')),
                ('logo_blanco', models.FileField(blank=True, null=True, upload_to='empresa/logo/')),
                ('logo_negro', models.FileField(blank=True, null=True, upload_to='empresa/logo/')),
                ('favicon', models.FileField(blank=True, null=True, upload_to='empresa/logo/')),
                ('imagen', models.FileField(blank=True, help_text='400x400', null=True, upload_to='empresa/logo/')),
                ('portada', models.FileField(blank=True, help_text='1280x400', null=True, upload_to='empresa/logo/')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '2. Zatuar Marca',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='proveedor/')),
                ('detalle', models.CharField(blank=True, max_length=300, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zatuar.ciudad')),
            ],
            options={
                'verbose_name_plural': '2. Proveedor',
            },
        ),
        migrations.CreateModel(
            name='Producto_Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('slider', models.FileField(blank=True, help_text='1884x529', null=True, upload_to='slider')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Zatuar.product')),
            ],
            options={
                'verbose_name_plural': '1. Slider',
            },
        ),
        migrations.CreateModel(
            name='Producto_Personalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to='producto')),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Zatuar.product')),
            ],
            options={
                'verbose_name_plural': '6. Producto Personalizacion',
            },
        ),
        migrations.CreateModel(
            name='Producto_Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0)),
                ('galeria_articulo', models.FileField(blank=True, help_text='imagen producto 800x800', null=True, upload_to='media')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Zatuar.product')),
            ],
            options={
                'verbose_name_plural': '5. Producto Imagenes',
            },
        ),
        migrations.CreateModel(
            name='Producto_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_producto', models.FileField(blank=True, help_text='500x500', null=True, upload_to='producto')),
                ('portada', models.FileField(blank=True, help_text='600x400', null=True, upload_to='producto')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Zatuar.cliente')),
            ],
            options={
                'verbose_name_plural': '7. Mandil Cliente',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zatuar.proveedor'),
        ),
        migrations.CreateModel(
            name='Galeria_Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galeria', models.FileField(blank=True, help_text='500x500', null=True, upload_to='cliente')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Zatuar.cliente')),
            ],
            options={
                'verbose_name_plural': '9.a Cliente Galeria',
            },
        ),
    ]
