# Generated by Django 4.0.6 on 2022-07-09 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zatuar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='product',
            name='proveedor',
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
