# Generated by Django 4.0.6 on 2022-07-09 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zatuar', '0002_remove_proveedor_ciudad_remove_product_proveedor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto_empresa',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='contacto_empresa',
            name='correo_personal',
        ),
        migrations.RemoveField(
            model_name='contacto_empresa',
            name='representante',
        ),
        migrations.RemoveField(
            model_name='redes_sociales',
            name='behance',
        ),
    ]
