# Generated by Django 4.0.6 on 2022-07-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zatuar', '0003_remove_contacto_empresa_calle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='client_logo',
            field=models.FileField(blank=True, help_text='200x200', null=True, upload_to='zatuar/'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.FileField(blank=True, help_text='1280x500', null=True, upload_to='zatuar/'),
        ),
        migrations.AlterField(
            model_name='descarga',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='zatuar/'),
        ),
        migrations.AlterField(
            model_name='descarga',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='zatuar/'),
        ),
        migrations.AlterField(
            model_name='detalles',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to='zatuar/'),
        ),
        migrations.AlterField(
            model_name='detalles',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='zatuar/'),
        ),
        migrations.AlterField(
            model_name='detalles',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to='zatuar/'),
        ),
        migrations.AlterField(
            model_name='galeria_cliente',
            name='galeria',
            field=models.FileField(blank=True, help_text='500x500', null=True, upload_to='zatuar/'),
        ),
        migrations.AlterField(
            model_name='galeria_proceso',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='zatuar/'),
        ),
        migrations.AlterField(
            model_name='personalizaion_poducto',
            name='imagen',
            field=models.FileField(upload_to='zatuar/'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='img1',
            field=models.FileField(blank=True, null=True, upload_to='zatuar/'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='img2',
            field=models.FileField(blank=True, null=True, upload_to='zatuar/'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='img3',
            field=models.FileField(blank=True, null=True, upload_to='zatuar/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='foto_slider',
            field=models.FileField(blank=True, null=True, upload_to='zatuar/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_a',
            field=models.FileField(blank=True, help_text='100x100', null=True, upload_to='zatuar/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_b',
            field=models.FileField(blank=True, help_text='100x100', null=True, upload_to='zatuar/'),
        ),
        migrations.AlterField(
            model_name='producto_cliente',
            name='imagen_producto',
            field=models.FileField(blank=True, help_text='500x500', null=True, upload_to='zatuar/'),
        ),
        migrations.AlterField(
            model_name='producto_cliente',
            name='portada',
            field=models.FileField(blank=True, help_text='600x400', null=True, upload_to='zatuar/'),
        ),
        migrations.AlterField(
            model_name='producto_imagen',
            name='galeria_articulo',
            field=models.FileField(blank=True, help_text='imagen producto 800x800', null=True, upload_to='zatuar/'),
        ),
        migrations.AlterField(
            model_name='producto_personalizacion',
            name='imagen',
            field=models.FileField(upload_to='zatuar/'),
        ),
        migrations.AlterField(
            model_name='producto_slider',
            name='slider',
            field=models.FileField(blank=True, help_text='1884x529', null=True, upload_to='zatuar/'),
        ),
        migrations.AlterField(
            model_name='zatuar_marca',
            name='favicon',
            field=models.FileField(blank=True, null=True, upload_to='zatuar/'),
        ),
        migrations.AlterField(
            model_name='zatuar_marca',
            name='imagen',
            field=models.FileField(blank=True, help_text='400x400', null=True, upload_to='zatuar/'),
        ),
        migrations.AlterField(
            model_name='zatuar_marca',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='zatuar/'),
        ),
        migrations.AlterField(
            model_name='zatuar_marca',
            name='logo_blanco',
            field=models.FileField(blank=True, null=True, upload_to='zatuar/'),
        ),
        migrations.AlterField(
            model_name='zatuar_marca',
            name='logo_negro',
            field=models.FileField(blank=True, null=True, upload_to='zatuar/'),
        ),
        migrations.AlterField(
            model_name='zatuar_marca',
            name='portada',
            field=models.FileField(blank=True, help_text='1280x400', null=True, upload_to='zatuar/'),
        ),
    ]
