# Generated by Django 4.0.6 on 2022-07-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zatuar', '0004_alter_cliente_client_logo_alter_cliente_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slider',
            field=models.FileField(blank=True, help_text='1884x529', null=True, upload_to='zatuar/'),
        ),
    ]
