# Generated by Django 4.0.6 on 2022-07-10 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zatuar', '0006_alter_beneficios_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name_plural': '01.0 Clientes'},
        ),
        migrations.AlterModelOptions(
            name='galeria_cliente',
            options={'verbose_name_plural': '01.1 Clientes-Galeria'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '9.4. Producto'},
        ),
        migrations.AlterModelOptions(
            name='producto_cliente',
            options={'verbose_name_plural': '9.9.1 Mandil Cliente'},
        ),
        migrations.AlterModelOptions(
            name='producto_imagen',
            options={'verbose_name_plural': '9.5. Producto Imagenes'},
        ),
        migrations.AlterModelOptions(
            name='producto_personalizacion',
            options={'verbose_name_plural': '9.6. Producto Personalizacion'},
        ),
        migrations.AlterModelOptions(
            name='producto_slider',
            options={'verbose_name_plural': '9.7. Slider'},
        ),
    ]
