# Generated by Django 4.0.6 on 2022-07-31 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Zatuar', '0007_alter_cliente_options_alter_galeria_cliente_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linea_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0)),
                ('linea', models.CharField(blank=True, max_length=50, null=True)),
                ('imagen', models.FileField(blank=True, help_text='100x100', null=True, upload_to='products/')),
            ],
            options={
                'verbose_name_plural': '9.3 Linea de Producto',
            },
        ),
        migrations.AlterModelOptions(
            name='clasif_producto',
            options={'verbose_name_plural': '9.4. Clasificaciòn de Producto'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '9.5. Producto'},
        ),
        migrations.AlterModelOptions(
            name='producto_imagen',
            options={'verbose_name_plural': '9.6. Producto Imagenes'},
        ),
        migrations.AlterModelOptions(
            name='producto_personalizacion',
            options={'verbose_name_plural': '9.7. Producto Personalizacion'},
        ),
        migrations.AlterModelOptions(
            name='producto_slider',
            options={'verbose_name_plural': '9.8. Slider'},
        ),
        migrations.AddField(
            model_name='product',
            name='ficha_tec',
            field=models.FileField(blank=True, help_text='pdf', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='orden',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clasif_producto',
            name='linea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Zatuar.linea_product'),
        ),
    ]
