# Generated by Django 4.0.6 on 2022-07-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zatuar', '0008_linea_product_alter_clasif_producto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zatuar_marca',
            name='imagen_2',
            field=models.FileField(blank=True, help_text='400x400', null=True, upload_to='zatuar/'),
        ),
    ]
