# Generated by Django 4.0.6 on 2024-09-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zatuar', '0009_zatuar_marca_imagen_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='blanco',
            field=models.BooleanField(default=False),
        ),
    ]
