# Generated by Django 4.0.6 on 2022-07-06 04:18

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '9.3. Categorias',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': '1. Ciudad',
            },
        ),
        migrations.CreateModel(
            name='Clasif_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion_producto', models.CharField(blank=True, max_length=90, null=True)),
            ],
            options={
                'verbose_name_plural': '3. Clasificaciòn de Producto',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=90, null=True)),
                ('sitio', models.CharField(blank=True, max_length=90, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='cliente')),
            ],
            options={
                'verbose_name_plural': '6. Imagenes / Video Servicios ',
            },
        ),
        migrations.CreateModel(
            name='Editables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_1_imagen', models.FileField(blank=True, null=True, upload_to='editable')),
                ('sec_1_titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('sec_1_detalle', models.TextField(blank=True, max_length=700, null=True)),
                ('sec_1_sub_1_icono_1', models.CharField(blank=True, max_length=100, null=True)),
                ('sec_1_sub_1_titulo_1', models.CharField(blank=True, max_length=100, null=True)),
                ('sec_1_sub_1_detalle_1', models.TextField(blank=True, max_length=700, null=True)),
                ('sec_1_sub_2_icono_1', models.CharField(blank=True, max_length=100, null=True)),
                ('sec_1_sub_2_titulo_1', models.CharField(blank=True, max_length=100, null=True)),
                ('sec_1_sub_2_detalle_1', models.TextField(blank=True, max_length=700, null=True)),
                ('sec_1_sub_3_icono_1', models.CharField(blank=True, max_length=100, null=True)),
                ('sec_1_sub_3_titulo_1', models.CharField(blank=True, max_length=100, null=True)),
                ('sec_1_sub_3_detalle_1', models.TextField(blank=True, max_length=700, null=True)),
                ('sec_2_imagen', models.FileField(blank=True, null=True, upload_to='editable')),
                ('sec_2_titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('sec_2_detalle', models.TextField(blank=True, max_length=700, null=True)),
                ('sec_2_sub_1_icono_1', models.CharField(blank=True, max_length=100, null=True)),
                ('sec_2_sub_1_titulo_1', models.CharField(blank=True, max_length=100, null=True)),
                ('sec_2_sub_1_detalle_1', models.TextField(blank=True, max_length=700, null=True)),
                ('sec_2_sub_2_icono_1', models.CharField(blank=True, max_length=100, null=True)),
                ('sec_2_sub_2_titulo_1', models.CharField(blank=True, max_length=100, null=True)),
                ('sec_2_sub_2_detalle_1', models.TextField(blank=True, max_length=700, null=True)),
                ('sec_2_sub_3_icono_1', models.CharField(blank=True, max_length=100, null=True)),
                ('sec_2_sub_3_titulo_1', models.CharField(blank=True, max_length=100, null=True)),
                ('sec_2_sub_3_detalle_1', models.TextField(blank=True, max_length=700, null=True)),
                ('sec_3_titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('sec_3_detalle', models.TextField(blank=True, max_length=700, null=True)),
                ('sec_3_sub_1_titulo_1', models.CharField(blank=True, max_length=100, null=True)),
                ('sec_3_sub_1_valor_1', models.CharField(blank=True, max_length=100, null=True)),
                ('sec_3_sub_2_titulo_1', models.CharField(blank=True, max_length=100, null=True)),
                ('sec_3_sub_2_valor_1', models.CharField(blank=True, max_length=100, null=True)),
                ('sec_3_sub_3_titulo_1', models.CharField(blank=True, max_length=100, null=True)),
                ('sec_3_sub_3_valor_1', models.CharField(blank=True, max_length=100, null=True)),
                ('sec_3_clientes', models.CharField(blank=True, max_length=100, null=True)),
                ('sec_3_proyectos', models.CharField(blank=True, max_length=100, null=True)),
                ('sec_3_anios_experiencia', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '3. Editable',
            },
        ),
        migrations.CreateModel(
            name='Frase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita', models.TextField(blank=True, null=True)),
                ('autor', models.CharField(blank=True, max_length=90, null=True)),
            ],
            options={
                'verbose_name_plural': '9.2. Frases',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='empresa')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresa')),
                ('logo_blanco', models.ImageField(blank=True, null=True, upload_to='empresa/')),
                ('logo_gris', models.ImageField(blank=True, null=True, upload_to='empresa')),
                ('logo_negro', models.ImageField(blank=True, null=True, upload_to='empresa')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='empresa')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('tiktok', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube', models.CharField(blank=True, max_length=100, null=True)),
                ('behance', models.CharField(blank=True, max_length=100, null=True)),
                ('estudio', models.TextField(blank=True, max_length=800, null=True)),
                ('mision', models.TextField(blank=True, max_length=400, null=True)),
                ('vision', models.TextField(blank=True, max_length=400, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
                ('valor_1_titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_1_detalle', models.TextField(blank=True, max_length=700, null=True)),
                ('valor_2_titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_2_detalle', models.TextField(blank=True, max_length=700, null=True)),
                ('valor_3_titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_3_detalle', models.TextField(blank=True, max_length=700, null=True)),
                ('valor_4_titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_4_detalle', models.TextField(blank=True, max_length=700, null=True)),
            ],
            options={
                'verbose_name_plural': '1. Marca',
            },
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portafolio', models.CharField(blank=True, max_length=90, null=True)),
                ('visualizaciones', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': '7. Tema Protafolio',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(blank=True, max_length=100, null=True)),
                ('stock', models.CharField(choices=[('stock', 'stock'), ('no_stock', 'no_stock')], default='stock', max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='producto/')),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True)),
                ('caracteristicas', ckeditor.fields.RichTextField(blank=True, max_length=500, null=True)),
                ('tamanos', models.TextField(blank=True, max_length=500, null=True)),
                ('material', models.TextField(blank=True, max_length=500, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('clasif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Girekstudio.clasif_producto')),
            ],
            options={
                'verbose_name_plural': '4. Producto',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('icono', models.CharField(blank=True, max_length=20, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicio')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.TextField(blank=True, default='', null=True)),
                ('info_1_icono', models.CharField(blank=True, max_length=50, null=True)),
                ('info_1_titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('info_1_descripcion', models.TextField(blank=True, default='', null=True)),
                ('info_2_icono', models.CharField(blank=True, max_length=50, null=True)),
                ('info_2_titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('info_2_descripcion', models.TextField(blank=True, default='', null=True)),
                ('info_3_icono', models.CharField(blank=True, max_length=50, null=True)),
                ('info_3_titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('info_3_descripcion', models.TextField(blank=True, default='', null=True)),
                ('info_4_icono', models.CharField(blank=True, max_length=50, null=True)),
                ('info_4_titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('info_4_descripcion', models.TextField(blank=True, default='', null=True)),
                ('info_5_icono', models.CharField(blank=True, max_length=50, null=True)),
                ('info_5_titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('info_5_descripcion', models.TextField(blank=True, default='', null=True)),
                ('info_6_icono', models.CharField(blank=True, max_length=50, null=True)),
                ('info_6_titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('info_6_descripcion', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'verbose_name_plural': '4. Servicios',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
            ],
            options={
                'verbose_name_plural': '9.2. Suscripción Email',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0)),
                ('fecha', models.DateField()),
                ('nombreproyecto', models.CharField(blank=True, help_text='Texto de maximo 120 caracteres', max_length=120, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('tipo_archivo', models.CharField(choices=[('imagen', 'imagen'), ('video_vertical', 'video_vertical'), ('video', 'video')], default='imagen', max_length=20)),
                ('imagen', models.FileField(blank=True, help_text='imagen producto 851x315', null=True, upload_to='portafolio/')),
                ('link', models.CharField(blank=True, max_length=250, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Girekstudio.cliente')),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Girekstudio.portafolio')),
            ],
            options={
                'verbose_name_plural': '8. Proyecto',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='proveedor/')),
                ('detalle', models.CharField(blank=True, max_length=300, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Girekstudio.ciudad')),
            ],
            options={
                'verbose_name_plural': '2. Proveedor',
            },
        ),
        migrations.CreateModel(
            name='Producto_Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galeria_articulo', models.ImageField(blank=True, help_text='imagen producto 800x800', null=True, upload_to='media')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Girekstudio.producto')),
            ],
            options={
                'verbose_name_plural': '5. Producto Imagenes',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Girekstudio.proveedor'),
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_activo', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('precio', models.CharField(blank=True, max_length=50, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('info_1', models.CharField(blank=True, max_length=100, null=True)),
                ('info_2', models.CharField(blank=True, max_length=100, null=True)),
                ('info_3', models.CharField(blank=True, max_length=100, null=True)),
                ('info_4', models.CharField(blank=True, max_length=100, null=True)),
                ('info_5', models.CharField(blank=True, max_length=100, null=True)),
                ('info_6', models.CharField(blank=True, max_length=100, null=True)),
                ('info_7', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Girekstudio.servicio')),
            ],
            options={
                'verbose_name_plural': '9.6. Planes',
            },
        ),
        migrations.CreateModel(
            name='Imagenesproyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galeriaproyecto', models.FileField(upload_to='galeriaproyecto/')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Girekstudio.proyecto')),
            ],
            options={
                'verbose_name_plural': '9. Proyecto Imagenes',
            },
        ),
        migrations.CreateModel(
            name='Imag_Video_Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('tipo_archivo', models.CharField(choices=[('imagen', 'imagen'), ('video', 'video')], default='imagen', max_length=20)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='servicio')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Girekstudio.servicio')),
            ],
            options={
                'verbose_name_plural': '5. Imagenes / Video Servicios ',
            },
        ),
        migrations.CreateModel(
            name='Contacto_empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('mapa', models.TextField(blank=True, max_length=500, null=True)),
                ('representante', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_personal', models.CharField(blank=True, max_length=100, null=True)),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
                ('celular2', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Girekstudio.ciudad')),
            ],
            options={
                'verbose_name_plural': '2. Contácto',
            },
        ),
    ]
