# Generated by Django 4.0.6 on 2022-07-10 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name_plural': 'PRODUCTOS- 01. Ciudad'},
        ),
        migrations.AlterModelOptions(
            name='clasif_producto',
            options={'verbose_name_plural': 'PRODUCTOS- 03. Clasificación de Producto'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name_plural': 'PROYECTOS- 01 Clientes '},
        ),
        migrations.AlterModelOptions(
            name='contacto_empresa',
            options={'verbose_name_plural': 'GIREKSTUDIO- 03 Contácto'},
        ),
        migrations.AlterModelOptions(
            name='editables',
            options={'verbose_name_plural': 'GIREKSTUDIO- 02 Editable'},
        ),
        migrations.AlterModelOptions(
            name='imag_video_servicio',
            options={'verbose_name_plural': 'SERVICIOS- 02 Imagenes / Video Servicios '},
        ),
        migrations.AlterModelOptions(
            name='imagenesproyecto',
            options={'verbose_name_plural': 'PROYECTOS- 04 Proyecto Imagenes'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'verbose_name_plural': 'GIREKSTUDIO- 01 Marca'},
        ),
        migrations.AlterModelOptions(
            name='planes',
            options={'verbose_name_plural': 'SERVICIO- 05 Planes'},
        ),
        migrations.AlterModelOptions(
            name='portafolio',
            options={'verbose_name_plural': 'PROYECTOS- 02 Tema Protafolio'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name_plural': 'PRODUCTOS- 04. Producto'},
        ),
        migrations.AlterModelOptions(
            name='producto_imagen',
            options={'verbose_name_plural': 'PRODUCTOS- 05. Producto Imagenes'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name_plural': 'PRODUCTOS- 02. Proveedor'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'verbose_name_plural': 'PROYECTOS- 03 Proyecto'},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'verbose_name_plural': 'SERVICIOS- 01 Servicios'},
        ),
    ]
