# Generated by Django 4.0.6 on 2022-07-10 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0002_alter_ciudad_options_alter_clasif_producto_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name_plural': 'PROD- 01. Ciudad'},
        ),
        migrations.AlterModelOptions(
            name='clasif_producto',
            options={'verbose_name_plural': 'PROD- 03. Clasificación de Producto'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name_plural': 'PROY- 01 Clientes '},
        ),
        migrations.AlterModelOptions(
            name='contacto_empresa',
            options={'verbose_name_plural': 'GI 04 Contácto'},
        ),
        migrations.AlterModelOptions(
            name='editables',
            options={'verbose_name_plural': 'GI- 02 Editable'},
        ),
        migrations.AlterModelOptions(
            name='frase',
            options={'verbose_name_plural': 'GI- 03 Frases'},
        ),
        migrations.AlterModelOptions(
            name='imag_video_servicio',
            options={'verbose_name_plural': 'SERV- 02 Imagenes / Video Servicios '},
        ),
        migrations.AlterModelOptions(
            name='imagenesproyecto',
            options={'verbose_name_plural': 'PROY- 04 Proyecto Imagenes'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'verbose_name_plural': 'GI- 01 Marca'},
        ),
        migrations.AlterModelOptions(
            name='planes',
            options={'verbose_name_plural': 'SERV- 03 Planes'},
        ),
        migrations.AlterModelOptions(
            name='portafolio',
            options={'verbose_name_plural': 'PROY- 02 Tema Protafolio'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name_plural': 'PROD- 04. Producto'},
        ),
        migrations.AlterModelOptions(
            name='producto_imagen',
            options={'verbose_name_plural': 'PROD- 05. Producto Imagenes'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name_plural': 'PROD- 02. Proveedor'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'verbose_name_plural': 'PROY- 03 Proyecto'},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'verbose_name_plural': 'SERV- 01 Servicios'},
        ),
    ]
