# Generated by Django 4.0.6 on 2022-07-10 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0003_delete_categoria_alter_ciudad_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto_empresa',
            options={'verbose_name_plural': 'GI- 04 Contácto'},
        ),
    ]
