# Generated by Django 4.0.6 on 2022-09-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0004_alter_contacto_empresa_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='girekstudio'),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_imagen',
            field=models.FileField(blank=True, null=True, upload_to='girekstudio/'),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_2_imagen',
            field=models.FileField(blank=True, null=True, upload_to='girekstudio/'),
        ),
        migrations.AlterField(
            model_name='imag_video_servicio',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='girekstudio/'),
        ),
        migrations.AlterField(
            model_name='imagenesproyecto',
            name='galeriaproyecto',
            field=models.FileField(upload_to='girekstudio/'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='girekstudio/'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='girekstudio/'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='girekstudio/'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='logo_blanco',
            field=models.ImageField(blank=True, null=True, upload_to='girekstudio/'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='logo_gris',
            field=models.ImageField(blank=True, null=True, upload_to='girekstudio/'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='logo_negro',
            field=models.ImageField(blank=True, null=True, upload_to='girekstudio/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='girekstudio/'),
        ),
        migrations.AlterField(
            model_name='producto_imagen',
            name='galeria_articulo',
            field=models.ImageField(blank=True, help_text='imagen producto 800x800', null=True, upload_to='girekstudio'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='girekstudio/'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='imagen',
            field=models.FileField(blank=True, help_text='imagen producto 851x315', null=True, upload_to='girekstudio/'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='girekstudio/'),
        ),
    ]
