# Generated by Django 4.1.1 on 2022-09-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0005_alter_cliente_logo_alter_editables_sec_1_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='caracteristicas',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
