# Generated by Django 4.0.6 on 2024-09-17 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0006_alter_producto_caracteristicas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(blank=True, null=True, upload_to='girekstudio')),
                ('nombre', models.CharField(blank=True, max_length=90, null=True)),
                ('cargo', models.CharField(blank=True, max_length=90, null=True)),
            ],
            options={
                'verbose_name_plural': 'TEAM- 01 Equipo de trabajo ',
            },
        ),
        migrations.CreateModel(
            name='Lista_servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista_serv', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'SERV- 01.1 Servicios Lista',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(blank=True, null=True, upload_to='girekstudio/')),
                ('titulo', models.CharField(blank=True, max_length=90, null=True)),
                ('sub_titulo', models.TextField(blank=True, max_length=500, null=True)),
                ('frase', models.CharField(blank=True, max_length=90, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(blank=True, max_length=90, null=True)),
                ('direccion', models.CharField(blank=True, max_length=90, null=True)),
                ('celular', models.CharField(blank=True, max_length=90, null=True)),
            ],
            options={
                'verbose_name_plural': 'TEAM- 01 Equipo de trabajo ',
            },
        ),
        migrations.DeleteModel(
            name='Suscripcion_Email',
        ),
        migrations.AlterModelOptions(
            name='editables',
            options={'verbose_name_plural': 'GI- 02 Editable pag Webs'},
        ),
        migrations.RenameField(
            model_name='editables',
            old_name='sec_1_imagen',
            new_name='sec_1_imagen_1',
        ),
        migrations.RenameField(
            model_name='editables',
            old_name='sec_2_imagen',
            new_name='sec_1_imagen_2',
        ),
        migrations.RenameField(
            model_name='editables',
            old_name='sec_1_sub_1_icono_1',
            new_name='sec_1_subti_1',
        ),
        migrations.RenameField(
            model_name='editables',
            old_name='sec_1_sub_1_titulo_1',
            new_name='sec_1_subti_2',
        ),
        migrations.RenameField(
            model_name='editables',
            old_name='sec_1_sub_2_icono_1',
            new_name='sec_1_subti_3',
        ),
        migrations.RenameField(
            model_name='editables',
            old_name='sec_1_sub_2_titulo_1',
            new_name='sec_1_subti_4',
        ),
        migrations.RenameField(
            model_name='editables',
            old_name='sec_1_sub_3_icono_1',
            new_name='sec_1_subti_5',
        ),
        migrations.RenameField(
            model_name='editables',
            old_name='sec_1_sub_3_titulo_1',
            new_name='sec_2_subti_4',
        ),
        migrations.RenameField(
            model_name='editables',
            old_name='sec_1_titulo',
            new_name='sec_2_subti_5',
        ),
        migrations.RemoveField(
            model_name='editables',
            name='sec_1_detalle',
        ),
        migrations.RemoveField(
            model_name='editables',
            name='sec_1_sub_1_detalle_1',
        ),
        migrations.RemoveField(
            model_name='editables',
            name='sec_1_sub_2_detalle_1',
        ),
        migrations.RemoveField(
            model_name='editables',
            name='sec_1_sub_3_detalle_1',
        ),
        migrations.RemoveField(
            model_name='editables',
            name='sec_2_detalle',
        ),
        migrations.RemoveField(
            model_name='editables',
            name='sec_2_sub_1_detalle_1',
        ),
        migrations.RemoveField(
            model_name='editables',
            name='sec_2_sub_1_icono_1',
        ),
        migrations.RemoveField(
            model_name='editables',
            name='sec_2_sub_1_titulo_1',
        ),
        migrations.RemoveField(
            model_name='editables',
            name='sec_2_sub_2_detalle_1',
        ),
        migrations.RemoveField(
            model_name='editables',
            name='sec_2_sub_2_icono_1',
        ),
        migrations.RemoveField(
            model_name='editables',
            name='sec_2_sub_2_titulo_1',
        ),
        migrations.RemoveField(
            model_name='editables',
            name='sec_2_sub_3_detalle_1',
        ),
        migrations.RemoveField(
            model_name='editables',
            name='sec_2_sub_3_icono_1',
        ),
        migrations.RemoveField(
            model_name='editables',
            name='sec_2_sub_3_titulo_1',
        ),
        migrations.RemoveField(
            model_name='editables',
            name='sec_2_titulo',
        ),
        migrations.RemoveField(
            model_name='editables',
            name='sec_3_anios_experiencia',
        ),
        migrations.RemoveField(
            model_name='editables',
            name='sec_3_clientes',
        ),
        migrations.RemoveField(
            model_name='editables',
            name='sec_3_detalle',
        ),
        migrations.RemoveField(
            model_name='editables',
            name='sec_3_proyectos',
        ),
        migrations.RemoveField(
            model_name='editables',
            name='sec_3_sub_1_titulo_1',
        ),
        migrations.RemoveField(
            model_name='editables',
            name='sec_3_sub_1_valor_1',
        ),
        migrations.RemoveField(
            model_name='editables',
            name='sec_3_sub_2_titulo_1',
        ),
        migrations.RemoveField(
            model_name='editables',
            name='sec_3_sub_2_valor_1',
        ),
        migrations.RemoveField(
            model_name='editables',
            name='sec_3_sub_3_titulo_1',
        ),
        migrations.RemoveField(
            model_name='editables',
            name='sec_3_sub_3_valor_1',
        ),
        migrations.RemoveField(
            model_name='editables',
            name='sec_3_titulo',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='estudio',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='mision',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='valor_1_detalle',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='valor_1_titulo',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='valor_2_detalle',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='valor_2_titulo',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='valor_3_detalle',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='valor_3_titulo',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='valor_4_detalle',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='valor_4_titulo',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='vision',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='info_1_descripcion',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='info_1_icono',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='info_1_titulo',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='info_2_descripcion',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='info_2_icono',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='info_2_titulo',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='info_3_descripcion',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='info_3_icono',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='info_3_titulo',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='info_4_descripcion',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='info_4_icono',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='info_4_titulo',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='info_5_descripcion',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='info_5_icono',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='info_5_titulo',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='info_6_descripcion',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='info_6_icono',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='info_6_titulo',
        ),
        migrations.AddField(
            model_name='editables',
            name='estudio',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='frase',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='mision',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_1_detalle_1',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_1_imagen_3',
            field=models.FileField(blank=True, null=True, upload_to='girekstudio/'),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_1_titulo_1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_1_titulo_2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_1_titulo_3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_1_titulo_4',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_1_titulo_5',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_1_titulo_6',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_2_anios_exper',
            field=models.CharField(blank=True, help_text='Anios de experiencia', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_2_anios_exper_detalle',
            field=models.CharField(blank=True, help_text='Detalle Crecimiento', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_2_clientes',
            field=models.CharField(blank=True, help_text='Numero de Clientes', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_2_clientes_detalle',
            field=models.CharField(blank=True, help_text='Detalle Clientes', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_2_crecimi',
            field=models.CharField(blank=True, help_text='Numero porcentaje crecimiento', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_2_crecimi_detalle',
            field=models.CharField(blank=True, help_text='Detalle crecimiento', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_2_detalle_4',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_2_detalle_5',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_2_encabezado',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_2_imagen_1',
            field=models.FileField(blank=True, help_text='Agencia encabezado imagen 1149x800', null=True, upload_to='girekstudio/'),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_2_imagen_3',
            field=models.FileField(blank=True, null=True, upload_to='girekstudio/'),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_2_imagen_4',
            field=models.FileField(blank=True, null=True, upload_to='girekstudio/'),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_2_imagen_5',
            field=models.FileField(blank=True, null=True, upload_to='girekstudio/'),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_2_imagen_6',
            field=models.FileField(blank=True, null=True, upload_to='girekstudio/'),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_2_proyectos',
            field=models.CharField(blank=True, help_text='Numero proyectos', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_2_proyectos_detalle',
            field=models.CharField(blank=True, help_text='Detalle proyectos', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_2_subti_1',
            field=models.CharField(blank=True, help_text='Agencia encabezado text verti', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_2_subti_2',
            field=models.CharField(blank=True, help_text='Agencia bajo de encabezado', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_2_subti_3',
            field=models.CharField(blank=True, help_text='Agencia texto rotativo', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_2_titulo_1',
            field=models.CharField(blank=True, help_text='Agencia encabezado text horiz', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_2_titulo_2',
            field=models.CharField(blank=True, help_text='Agencia bajo de encabezado', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_2_titulo_4',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_2_titulo_5',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_3_imagen_1',
            field=models.FileField(blank=True, help_text='Servicios encabezado imagen 1149x800', null=True, upload_to='girekstudio/'),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_3_subti_1',
            field=models.CharField(blank=True, help_text='Servicios encabezado text verti', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_3_subti_2',
            field=models.CharField(blank=True, help_text='Servicios bajo de encabezado', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_3_subti_3',
            field=models.CharField(blank=True, help_text='Servicios texto rotativo', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_3_titulo_1',
            field=models.CharField(blank=True, help_text='Servicios encabezado text horiz', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_3_titulo_2',
            field=models.CharField(blank=True, help_text='Servicios bajo de encabezado', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_4_rotativo',
            field=models.CharField(blank=True, help_text='Portafolio texto rotativo', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_4_subti_1',
            field=models.CharField(blank=True, help_text='Portafolio encabezado ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_4_titulo_1',
            field=models.CharField(blank=True, help_text='Portafolio encabezado', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_5_imagen_1',
            field=models.FileField(blank=True, help_text='Contacto encabezado imagen 1149x800', null=True, upload_to='girekstudio/'),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_5_imagen_2',
            field=models.FileField(blank=True, help_text='Contacto encabezado imagen 1149x800', null=True, upload_to='girekstudio/'),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_5_subti_1',
            field=models.CharField(blank=True, help_text='Contacto encabezado text verti', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_5_titulo_1',
            field=models.CharField(blank=True, help_text='Contacto encabezado text horiz', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='vision',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='imagenesproyecto',
            name='imagen_cuadra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagenesproyecto',
            name='imagen_rectang',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planes',
            name='info_10',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='planes',
            name='info_8',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='planes',
            name='info_9',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='planes',
            name='sub_info_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='planes',
            name='sub_info_10',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='planes',
            name='sub_info_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='planes',
            name='sub_info_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='planes',
            name='sub_info_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='planes',
            name='sub_info_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='planes',
            name='sub_info_6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='planes',
            name='sub_info_7',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='planes',
            name='sub_info_8',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='planes',
            name='sub_info_9',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='detalle_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='imag_serv_1',
            field=models.ImageField(blank=True, null=True, upload_to='girekstudio/'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='imag_serv_2',
            field=models.ImageField(blank=True, null=True, upload_to='girekstudio/'),
        ),
        migrations.AddField(
            model_name='lista_servicio',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Girekstudio.servicio'),
        ),
    ]
