# Generated by Django 4.0.6 on 2024-09-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0007_equipo_lista_servicio_slider_sucursales_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto_empresa',
            old_name='correo_personal',
            new_name='behance',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='behance',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='tiktok',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='youtube',
        ),
        migrations.AddField(
            model_name='contacto_empresa',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contacto_empresa',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contacto_empresa',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contacto_empresa',
            name='tiktok',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contacto_empresa',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contacto_empresa',
            name='youtube',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_1_imagen_01',
            field=models.FileField(blank=True, help_text='Inicio encabezado imagen 1149x800', null=True, upload_to='girekstudio/'),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_1_imagen_02',
            field=models.FileField(blank=True, help_text='Inicio encabezado imagen 1149x800', null=True, upload_to='girekstudio/'),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_1_imagen_03',
            field=models.FileField(blank=True, help_text='Inicio encabezado imagen 1149x800', null=True, upload_to='girekstudio/'),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_1_subsubti_01',
            field=models.CharField(blank=True, help_text='Inicio texto vertical', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_1_subti_01',
            field=models.CharField(blank=True, help_text='Inicio primer subtitulo', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_1_titulo_01',
            field=models.CharField(blank=True, help_text='Inicio primer titulo', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_1_titulo_7',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='foto_2',
            field=models.FileField(blank=True, null=True, upload_to='girekstudio'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='dark',
            field=models.BooleanField(default=False, help_text='Activar en numeros impar - tono gris en fondo'),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_imagen_1',
            field=models.FileField(blank=True, help_text='Inicio  imagen 421x524', null=True, upload_to='girekstudio/'),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_imagen_2',
            field=models.FileField(blank=True, help_text='Inicio  imagen 421x524', null=True, upload_to='girekstudio/'),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_imagen_3',
            field=models.FileField(blank=True, help_text='Inicio  imagen 421x524', null=True, upload_to='girekstudio/'),
        ),
    ]
