# Generated by Django 4.0.6 on 2024-09-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0008_rename_correo_personal_contacto_empresa_behance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editables',
            name='sec_2_subti_3',
        ),
        migrations.RemoveField(
            model_name='editables',
            name='sec_3_subti_3',
        ),
        migrations.RemoveField(
            model_name='editables',
            name='sec_4_rotativo',
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_3_imagen',
            field=models.FileField(blank=True, help_text='Agencia texto rotativo', null=True, upload_to='girekstudio/'),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_4_imagen',
            field=models.FileField(blank=True, help_text='Agencia texto rotativo', null=True, upload_to='girekstudio/'),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_subsubti_01',
            field=models.CharField(blank=True, help_text='Inicio texto vertical', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_subti_01',
            field=models.CharField(blank=True, help_text='Inicio primer subtitulo', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_subti_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_subti_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_subti_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_subti_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_subti_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_titulo_01',
            field=models.CharField(blank=True, help_text='Inicio primer titulo', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_titulo_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_titulo_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_titulo_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_titulo_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_titulo_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_titulo_6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_titulo_7',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_2_anios_exper',
            field=models.CharField(blank=True, help_text='Anios de experiencia', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_2_anios_exper_detalle',
            field=models.CharField(blank=True, help_text='Detalle Crecimiento', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_2_clientes',
            field=models.CharField(blank=True, help_text='Numero de Clientes', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_2_clientes_detalle',
            field=models.CharField(blank=True, help_text='Detalle Clientes', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_2_crecimi',
            field=models.CharField(blank=True, help_text='Numero porcentaje crecimiento', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_2_crecimi_detalle',
            field=models.CharField(blank=True, help_text='Detalle crecimiento', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_2_encabezado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_2_imagen_1',
            field=models.FileField(blank=True, help_text='Agencia texto rotativo', null=True, upload_to='girekstudio/'),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_2_proyectos',
            field=models.CharField(blank=True, help_text='Numero proyectos', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_2_proyectos_detalle',
            field=models.CharField(blank=True, help_text='Detalle proyectos', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_2_subti_1',
            field=models.CharField(blank=True, help_text='Agencia encabezado text verti', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_2_subti_2',
            field=models.CharField(blank=True, help_text='Agencia bajo de encabezado', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_2_subti_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_2_subti_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_2_titulo_1',
            field=models.CharField(blank=True, help_text='Agencia encabezado text horiz', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_2_titulo_2',
            field=models.CharField(blank=True, help_text='Agencia bajo de encabezado', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_2_titulo_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_2_titulo_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_3_subti_1',
            field=models.CharField(blank=True, help_text='Servicios encabezado text verti', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_3_subti_2',
            field=models.CharField(blank=True, help_text='Servicios bajo de encabezado', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_3_titulo_1',
            field=models.CharField(blank=True, help_text='Servicios encabezado text horiz', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_3_titulo_2',
            field=models.CharField(blank=True, help_text='Servicios bajo de encabezado', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_4_subti_1',
            field=models.CharField(blank=True, help_text='Portafolio encabezado ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_4_titulo_1',
            field=models.CharField(blank=True, help_text='Portafolio encabezado', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_5_subti_1',
            field=models.CharField(blank=True, help_text='Contacto encabezado text verti', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_5_titulo_1',
            field=models.CharField(blank=True, help_text='Contacto encabezado text horiz', max_length=200, null=True),
        ),
    ]
