# Generated by Django 4.0.6 on 2024-09-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0009_remove_editables_sec_2_subti_3_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursales',
            options={'verbose_name_plural': 'TEAM- 02 Sucursales '},
        ),
        migrations.AddField(
            model_name='servicio',
            name='imag_serv_princi',
            field=models.ImageField(blank=True, help_text='Imagen principal Inicio', null=True, upload_to='girekstudio/'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='inicio',
            field=models.BooleanField(default=False, help_text='Para Ver en Inicio'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='linen',
            field=models.BooleanField(default=False, help_text='Activar en numeros impar - tono claro en fondo'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='dark',
            field=models.BooleanField(default=False, help_text='Activar en numeros par - tono gris en fondo'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='imag_serv_1',
            field=models.ImageField(blank=True, help_text='Imagen horizontal', null=True, upload_to='girekstudio/'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='imag_serv_2',
            field=models.ImageField(blank=True, help_text='Imagen cuadrada', null=True, upload_to='girekstudio/'),
        ),
    ]
