# Generated by Django 4.0.6 on 2024-09-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0010_alter_sucursales_options_servicio_imag_serv_princi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='dark',
            new_name='line',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='linen',
            new_name='white',
        ),
    ]
