# Generated by Django 4.0.6 on 2024-09-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0011_rename_dark_servicio_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editables',
            name='sec_1_imagen_4',
            field=models.FileField(blank=True, help_text='imagen pie de pag 1126x630', null=True, upload_to='girekstudio/'),
        ),
    ]
