# Generated by Django 4.0.6 on 2024-09-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0014_editables_sec_2_imagen_rota'),
    ]

    operations = [
        migrations.AddField(
            model_name='editables',
            name='sec_2_imag_rota_ico',
            field=models.FileField(blank=True, help_text='Agencia texto rotativo', null=True, upload_to='girekstudio/'),
        ),
    ]
