# Generated by Django 4.0.6 on 2024-09-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0015_editables_sec_2_imag_rota_ico'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista_servicio',
            name='Segunda_colu',
            field=models.BooleanField(default=False, help_text='Activar para enviar a segunda columna'),
        ),
    ]
