# Generated by Django 4.0.6 on 2024-09-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0016_lista_servicio_segunda_colu'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista_servicio',
            name='primera_colu',
            field=models.BooleanField(default=False, help_text='Activar para enviar a primera columna'),
        ),
        migrations.AlterField(
            model_name='lista_servicio',
            name='lista_serv',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
