# Generated by Django 4.0.6 on 2024-09-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0017_lista_servicio_primera_colu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='img_dere',
            field=models.BooleanField(default=False, help_text='Sec Agencia para cambiar orden de img activar para par'),
        ),
    ]
