# Generated by Django 4.0.6 on 2024-09-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0019_remove_servicio_img_dere_servicio_img_direc'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='imagen_rota',
            field=models.FileField(blank=True, help_text='servicios texto rotativo', null=True, upload_to='girekstudio/'),
        ),
    ]
