# Generated by Django 4.0.6 on 2024-09-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0020_servicio_imagen_rota'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='imag_rota_ico',
            field=models.FileField(blank=True, help_text='Agencia texto rotativo', null=True, upload_to='girekstudio/'),
        ),
    ]
