# Generated by Django 4.0.6 on 2024-09-19 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0021_servicio_imag_rota_ico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0)),
                ('info_1', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_info_1', models.CharField(blank=True, max_length=100, null=True)),
                ('plan_serv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Girekstudio.planes')),
            ],
            options={
                'verbose_name_plural': 'SERV- 03.5 Plan Lista ',
            },
        ),
    ]
