# Generated by Django 4.0.6 on 2024-09-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0022_plan_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planes',
            old_name='info_1',
            new_name='sub_titulo',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='info_10',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='info_2',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='info_3',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='info_4',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='info_5',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='info_6',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='info_7',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='info_8',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='info_9',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='sub_info_1',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='sub_info_10',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='sub_info_2',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='sub_info_3',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='sub_info_4',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='sub_info_5',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='sub_info_6',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='sub_info_7',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='sub_info_8',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='sub_info_9',
        ),
        migrations.AlterField(
            model_name='planes',
            name='precio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='planes',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
