# Generated by Django 4.0.6 on 2024-09-19 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0023_rename_info_1_planes_sub_titulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan_list',
            name='sub_info_1',
        ),
    ]
