# Generated by Django 4.0.6 on 2024-09-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0024_remove_plan_list_sub_info_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='video_link',
            field=models.CharField(blank=True, help_text='Pegar link video de youtube', max_length=500, null=True),
        ),
    ]
