# Generated by Django 4.0.6 on 2024-09-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0025_servicio_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='palabra',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
