# Generated by Django 4.0.6 on 2024-09-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0026_servicio_palabra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editables',
            name='sec_4_subti_1',
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_4_detalle',
            field=models.TextField(blank=True, help_text='Portafolio Detalle encabezado', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_4_imag_rota_ico',
            field=models.FileField(blank=True, help_text='Portafolio icono ', null=True, upload_to='girekstudio/'),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_4_imagen',
            field=models.FileField(blank=True, help_text='Portafolio texto rotativo', null=True, upload_to='girekstudio/'),
        ),
    ]
