# Generated by Django 4.0.6 on 2024-09-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0028_proyecto_img_central_proyecto_img_dere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='imagen_rectang',
            field=models.FileField(blank=True, help_text='imagen proyecto rectangular 851x315', null=True, upload_to='girekstudio/'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='imagen',
            field=models.FileField(blank=True, help_text='imagen proyecto 851x315', null=True, upload_to='girekstudio/'),
        ),
    ]
