# Generated by Django 4.0.6 on 2024-09-21 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0029_proyecto_imagen_rectang_alter_proyecto_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenesproyecto',
            old_name='imagen_rectang',
            new_name='imagen_rectangu',
        ),
    ]
