# Generated by Django 4.0.6 on 2024-09-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0031_remove_editables_sec_2_imagen_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editables',
            name='sec_2_subti_2',
        ),
        migrations.AddField(
            model_name='editables',
            name='sec_2_palabra',
            field=models.CharField(blank=True, help_text='Agencia bajo de encabezado palabra ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='frase',
            field=models.CharField(blank=True, help_text='Frase movimiento', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_detalle_1',
            field=models.TextField(blank=True, help_text='Bajo de encabezado', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_imagen_01',
            field=models.FileField(blank=True, help_text='Encabezado slider  1149x800', null=True, upload_to='girekstudio/'),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_imagen_02',
            field=models.FileField(blank=True, help_text='Encabezado slider 1149x800', null=True, upload_to='girekstudio/'),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_imagen_03',
            field=models.FileField(blank=True, help_text='Encabezado slider 1149x800', null=True, upload_to='girekstudio/'),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_imagen_1',
            field=models.FileField(blank=True, help_text='Bajo de encabezado  imagen 421x524', null=True, upload_to='girekstudio/'),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_imagen_2',
            field=models.FileField(blank=True, help_text='Bajo de encabezado  imagen 500x614', null=True, upload_to='girekstudio/'),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_imagen_3',
            field=models.FileField(blank=True, help_text='Bajo de encabezado  imagen 261x313', null=True, upload_to='girekstudio/'),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_subsubti_01',
            field=models.CharField(blank=True, help_text='Encabezado Texto Vertical', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_subti_01',
            field=models.CharField(blank=True, help_text='Encabezado  subtitulo', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_subti_1',
            field=models.CharField(blank=True, help_text='Bajo de encabezado', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_subti_2',
            field=models.CharField(blank=True, help_text='Bajo de servicio', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_subti_3',
            field=models.CharField(blank=True, help_text='Opcion detalle 1', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_subti_4',
            field=models.CharField(blank=True, help_text='Opcion detalle 2', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_subti_5',
            field=models.CharField(blank=True, help_text='Opcion detalle 3', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_titulo_01',
            field=models.CharField(blank=True, help_text='Encabezado  Titulo', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_titulo_1',
            field=models.CharField(blank=True, help_text='Bajo de encabezado', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_titulo_2',
            field=models.CharField(blank=True, help_text='Bajo de servicio', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_titulo_3',
            field=models.CharField(blank=True, help_text='Opcion Titulo 1', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_titulo_4',
            field=models.CharField(blank=True, help_text='Opcion Titulo 2', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_titulo_5',
            field=models.CharField(blank=True, help_text='Opcion Titulo 3', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_titulo_6',
            field=models.CharField(blank=True, help_text='Bajo parte izq. de equipo', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_1_titulo_7',
            field=models.CharField(blank=True, help_text='Pie de pag izq. frase', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_2_detalle_4',
            field=models.TextField(blank=True, help_text='Detalle lado derecho', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_2_detalle_5',
            field=models.TextField(blank=True, help_text='5', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_2_encabezado',
            field=models.CharField(blank=True, help_text='2', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_2_imagen_3',
            field=models.FileField(blank=True, help_text='Bajo de encabezado  imagen 421x524', null=True, upload_to='girekstudio/'),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_2_imagen_4',
            field=models.FileField(blank=True, help_text='Bajo de encabezado  imagen 500x614', null=True, upload_to='girekstudio/'),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_2_imagen_5',
            field=models.FileField(blank=True, help_text='Bajo de encabezado  imagen 261x313', null=True, upload_to='girekstudio/'),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_2_imagen_6',
            field=models.FileField(blank=True, help_text='1', null=True, upload_to='girekstudio/'),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_2_subti_4',
            field=models.CharField(blank=True, help_text='Subtitulo pequeño lado derecho', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_2_subti_5',
            field=models.CharField(blank=True, help_text='4', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_2_titulo_4',
            field=models.CharField(blank=True, help_text='Titulo grande lado derecho', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_2_titulo_5',
            field=models.CharField(blank=True, help_text='3', max_length=200, null=True),
        ),
    ]
